eureka:
  client:
    register-with-eureka: true
server:
  port: 8085
spring:
        application:
               name: API_Gateway              
        cloud: 
          gateway:
            routes:
            - id: Admin
              uri: http://localhost:8081/
              predicates:
              - Path=/admin/**
              filters:
              - StripPrefix=1
            - id: User
              uri: http://localhost:8084/
              predicates:
              - Path=/search/**
              filters:
              - StripPrefix=1
            - id: Payment
              uri: http://localhost:8083/
              predicates:
              - Path=/pay/**
              filters:
              - StripPrefix=1
            - id: CheckIn
              uri: http://localhost:8086/
              predicates:
              - Path=/checkIn/**
              filters:
              - StripPrefix=1
            - id: Book
              uri: http://localhost:8082/
              predicates:
              - Path=/user/**
              filters:
              - StripPrefix=1
            

             